### ISSUE TITLE
close a connect

### ISSUE THREAD

**Issue by lengqi127** [nakagami/pydrda#4] opened 2019-12-02 02:57 UTC
Hi,

i have encountered an error while querying in a test database. When I run

cur.execute('select * from syscat.tables where tabschema = current schema')
get the following error :
Traceback (most recent call last):
  File "D:\admin\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "D:\admin\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\admin\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\admin\PyCharm Community Edition 2019.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/exe/DB2Test/pydrda-master/db2Example.py", line 5, in <module>
    cur.execute('select * from syscat.tables where tabschema = current schema')
  File "D:\exe\DB2Test\pydrda-master\drda\cursor.py", line 62, in execute
    self._rows, self.description = self.connection._query(self.query, args)
  File "D:\exe\DB2Test\pydrda-master\drda\connection.py", line 389, in _query
    rows, description, params_description = self._parse_response()
  File "D:\exe\DB2Test\pydrda-master\drda\connection.py", line 50, in _parse_response
    dds_type, chained, number, code_point, obj = ddm.read_dds(self.sock)
  File "D:\exe\DB2Test\pydrda-master\drda\ddm.py", line 229, in read_dds
    b = _recv_from_sock(sock, 6)
  File "D:\exe\DB2Test\pydrda-master\drda\ddm.py", line 38, in _recv_from_sock
    bs = sock.recv(n)
ConnectionResetError: [WinError 10054]

**Comment by nakagami** [comment] 2021-11-29 23:32
The cause is unknown, but checking the user/password may help.

I'm going to close this issue now, since I don't know what's going on anymore.

**Closed by nakagami** 2021-11-29 23:32 UTC
